---
abstract: 'A lightweight module for running processes synchronously'
author:
  - 'jason hord <pravus@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.00
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Proc-Lite
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0.00
  Errno: 0.00
  IO::Pipe: 0.00
  IO::Select: 0.00
  POSIX: 0.00
  Test::More: 0.00
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.08
